# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd0e0b103c060697c00c058fceaeba9459bd63a37d453304741db7aceeae82f625cf050922821e702d3d9fcb32a4059bb57af6a6b4cb53644bc0b1d06f62940d

test:
  secret_key_base: ed14b71c220ec4d8c98411fe1b08decd34698ae27bda2d0656f5001984163e613b2ef4ace846d637cbd82ea91b38297d216d149259822641ed2854192e6d0205

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
